# Docker swarm demo for cronicle cluster

# Before you start:
# make sure your docker engine is in swarm mode
# build a local cronicle-edge image: docker build -t cronicle:edge -f Dockerfile .
# create cronicle secret: echo myPassword123 | docker secret create secret_key -

# start cluster:         docker stack deploy --compose-file  LocalCluster.yaml cron_stack
# check status:          docker stack ps cron_stack
# check logs on error:   docker service logs cron_stack_manager1
# remove cluster:        docker stack rm cron_stack

version: '3.8'
services:
  worker1:
    image: cronicle/cronicle:edge
    hostname: worker1
    ports: 
      - "3013:3012"
    networks:
      - cw
    deploy:
      replicas: 1
    entrypoint: worker
    secrets:
      - source: "secret_key"
        target: "secret_key"
        uid: "0"
        gid: "0"
        mode: 0400

  worker2:
    image: cronicle/cronicle:edge
    hostname: worker2
    ports: 
      - "3014:3012"
    networks:
      - cw
    deploy:
      replicas: 1
    entrypoint: worker
    secrets:
      - source: "secret_key"
        target: "secret_key"
        uid: "0"
        gid: "0"
        mode: 0400
 
  manager1:
    image: cronicle/cronicle:edge
    hostname: manager1
    ports: 
      - "3012:3012"
    networks:
      - cw
    deploy:
      replicas: 1
    entrypoint: manager 
    secrets:
      - source: "secret_key"
        target: "secret_key"
        uid: "0"
        gid: "0"
        mode: 0400
    environment:
      - "CRONICLE_manager=1"

networks:
  cw:
    driver: overlay
    attachable: true
    
secrets:
  secret_key:
    external: true

# once manager1 is up and running go to Add Server menu and add worker1 and worker2
