name: Docker Build Arm64

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      env:
        DOCKER_USERNAME: ${{ secrets.DHUB_USER }}
        DOCKER_PASSWORD: ${{ secrets.DHUB_TOKEN }}
      with:
        context: .
        file: ./Docker/arm64.dockerfile
        platforms: linux/arm64
        push: true
        tags: docker.io/cronicle/edge:arm64

